name: Build OPlus KernelSU Next
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm7675'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_ace_3v_v'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'pineapple'

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - name: Maximize build
       uses: easimon/maximize-build-space@master
       with:
         swap-size-mb: 8192
         root-reserve-mb: 4096
         temp-reserve-mb: 4096
         remove-dotnet: 'true'
         remove-android: 'true'
         remove-haskell: 'true'
         
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Configure Git
       run: |
        git config --global user.name "wuua"
        git config --global user.email "3436678798@qq.com"

     - name: Clean up disk space
       run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet /etc/mysql /var/lib/mysql
        sudo rm -rf /usr/local/lib/android
        df -h
        
     - name: Install dependencies
       run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y python3 git curl

     - name: Install repo tool
       run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

     - name: Initialize repo and sync
       run: |
        mkdir kernel_workspace && cd kernel_workspace
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
        repo sync
        rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
        rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
        sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
        sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion

     - name: Set up KernelSU
       run: |
        cd kernel_workspace/kernel_platform/common
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
        cd KernelSU-Next
        KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
        sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
        
     - name: Build kernel
       run: |
        cd kernel_workspace
        ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ github.event.inputs.CPUD }} gki

     - name: Make AnyKernel3
       run: |
        git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
        rm -rf ./AnyKernel3/.git
        cp kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/dist/Image ./AnyKernel3/
        7z a AnyKernel3-KernelSU-Next-${{ env.KSUVER }}-A15-${{ github.event.inputs.FEIL }}.zip ./AnyKernel3/*

     - name: Upload Release
       uses: ncipollo/release-action@main
       with:
        artifacts: ${{ github.workspace }}/AnyKernel3/*
        name: ${{ github.event.inputs.FEIL }}
        tag: ${{ github.event.inputs.FEIL }}-${{ env.KSUVER }}
        allowUpdates: true
        artifactErrorsFailBuild: true
          
     - name: Upload AnyKernel3
       uses: actions/upload-artifact@v4
       with:
        name: AnyKernel3-KernelSU-Next-${{ env.KSUVER }}-A15-${{ github.event.inputs.FEIL }}
        path: ./AnyKernel3/*

     - name: Upload kernel Image
       uses: actions/upload-artifact@v4
       with:
        name: Image-KernelSU-Next-${{ env.KSUVER }}-A15-${{ github.event.inputs.FEIL }}
        path: kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/dist/Image

     - name: Upload boot.img
       uses: actions/upload-artifact@v4
       with:
        name: boot-KernelSU-Next-${{ env.KSUVER }}-A15-${{ github.event.inputs.FEIL }}
        path: kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/dist/boot.img
